location = /semantic-layer-planner {
    return 302 /semantic-layer-planner/;
}

location /semantic-layer-planner/ {
    set $semantic_layer_planner_api_upstream http://semantic-layer-planner-api:8000;
    rewrite ^/semantic\-layer\-planner/(.*)$ /$1 break;
    proxy_pass $semantic_layer_planner_api_upstream;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
}
