location /prefect/api/ {
    rewrite ^/prefect/api/(.*)$ /api/$1 break;
    proxy_pass $prefect_upstream;
    proxy_read_timeout 300s;
}

location = /prefect {
    return 302 /prefect/;
}

location /prefect/assets/ {
    proxy_pass $prefect_upstream;
    proxy_read_timeout 300s;
}

location /prefect/ico/ {
    proxy_pass $prefect_upstream;
    proxy_read_timeout 300s;
}

location /prefect/ {
    proxy_pass $prefect_upstream;
    proxy_read_timeout 300s;
}

location /assets/ {
    proxy_pass $prefect_upstream;
    proxy_read_timeout 300s;
}

location /ico/ {
    proxy_pass $prefect_upstream;
    proxy_read_timeout 300s;
}

location = /favicon.ico {
    proxy_pass $prefect_upstream;
    proxy_read_timeout 300s;
}

location = /favicon-dark.ico {
    proxy_pass $prefect_upstream;
    proxy_read_timeout 300s;
}
