location = /pubdata-mcp {
    return 302 /pubdata-mcp/;
}

location /pubdata-mcp/ {
    set $pubdata_mcp_upstream http://pubdata-mcp:8000;
    rewrite ^/pubdata\-mcp/(.*)$ /$1 break;
    proxy_pass $pubdata_mcp_upstream;
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}
