location = /semantic-platform-planner {
    return 302 /semantic-platform-planner/;
}

location /semantic-platform-planner/ {
    set $semantic_platform_planner_api_upstream http://semantic-platform-planner-api:8000;
    rewrite ^/semantic\-platform\-planner/(.*)$ /$1 break;
    proxy_pass $semantic_platform_planner_api_upstream;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
}
