location = /semantic {
    set $semantic_platform_dashboard_upstream http://semantic-platform-dashboard:3000;
    proxy_pass $semantic_platform_dashboard_upstream;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
}

location /semantic/ {
    set $semantic_platform_dashboard_upstream http://semantic-platform-dashboard:3000;
    proxy_pass $semantic_platform_dashboard_upstream;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
}
