location = /data-score {
    return 302 /data-score/;
}

location /data-score/ {
    set $data_score_api_upstream http://data-score-api:8000;
    rewrite ^/data\-score/(.*)$ /$1 break;
    proxy_pass $data_score_api_upstream;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}
