import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from core.catalog.platform_service_catalog import list_active_platform_service_definitions
from core.catalog.app_service_catalog import list_app_service_definitions
from core.catalog.service_catalog import list_service_definitions

COMPOSE_OUTPUT_PATH = PROJECT_ROOT / "deploy" / "compose" / "docker-compose.yml"


def _indent(text: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" if line else line for line in text.splitlines())


def _render_platform_service(definition) -> str:
    lines = [f"{definition.service_name}:"]
    if definition.image is not None:
        lines.append(f"  image: {definition.image}")
        if definition.service_name == "redis":
            lines.append('  command: ["redis-server", "/usr/local/etc/redis/redis.conf"]')
    if definition.dockerfile is not None:
        lines.extend(
            [
                "  build:",
                f"    context: {definition.build_context}",
                f"    dockerfile: {definition.dockerfile}",
            ]
        )
    if definition.command:
        lines.append(f"  command: [{', '.join(_quote_healthcheck_item(item) for item in definition.command)}]")
    if definition.user is not None:
        lines.append(f'  user: "{definition.user}"')
    if definition.restart is not None:
        lines.append(f"  restart: {definition.restart}")
    if definition.env_files:
        lines.append("  env_file:")
        lines.extend(f"    - {_to_compose_env_file_path(path)}" for path in definition.env_files)
    if definition.ports:
        lines.append("  ports:")
        lines.extend(f'    - "{port}"' for port in definition.ports)
    if definition.volumes:
        lines.append("  volumes:")
        lines.extend(f"    - {_to_compose_volume(volume)}" for volume in definition.volumes)
    if definition.depends_on_service_healthy:
        lines.append("  depends_on:")
        for service_name in definition.depends_on_service_healthy:
            lines.extend(
                [
                    f"    {service_name}:",
                    "      condition: service_healthy",
                ]
            )
    if definition.healthcheck is not None:
        lines.extend(
            [
                "  healthcheck:",
                f"    test: [{', '.join(_quote_healthcheck_item(item) for item in definition.healthcheck.test)}]",
                f"    interval: {definition.healthcheck.interval}",
                f"    timeout: {definition.healthcheck.timeout}",
                f"    retries: {definition.healthcheck.retries}",
            ]
        )
    return "\n".join(lines)


def _render_worker_service(definition) -> str:
    env_files = "\n".join(f"    - {_to_compose_env_file_path(path)}" for path in definition.env_files)
    return f"""{definition.service_name}:
  build:
    context: ../..
    dockerfile: {definition.dockerfile}
  user: "${{HOST_UID:-1000}}:${{HOST_GID:-1000}}"
  restart: unless-stopped
  env_file:
{env_files}
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
  deploy:
    replicas: {definition.replicas}"""


def _to_compose_path(path: str) -> str:
    normalized = Path(path).as_posix()
    if normalized.startswith("deploy/compose/"):
        return normalized.removeprefix("deploy/compose/")
    if normalized.startswith("core/"):
        return f"../../{normalized}"
    return normalized


def _to_compose_env_file_path(path: str) -> str:
    normalized = Path(path).as_posix()
    if normalized.startswith("deploy/compose/"):
        return f"./{normalized.removeprefix('deploy/compose/')}"
    return f"../../{normalized}"


def _to_compose_volume(volume: str) -> str:
    source, separator, target = volume.partition(":")
    if not separator:
        return volume
    if source.startswith("${") or source.startswith("/") or source.startswith("."):
        return volume
    return f"{_to_compose_path(source)}:{target}"


def _quote_healthcheck_item(value: str) -> str:
    return f'"{value}"'


def render_compose() -> str:
    service_blocks = [_render_platform_service(definition) for definition in list_active_platform_service_definitions()]
    service_blocks.extend(
        _render_platform_service(definition)
        for definition in list_app_service_definitions()
    )
    for definition in list_service_definitions():
        service_blocks.append(_render_worker_service(definition))

    body = "\n\n".join(_indent(block, 2) for block in service_blocks)
    return (
        "# Generated by scripts/generate_compose.py\n"
        "# Source of truth: core/**/manifests + apps/**/manifests + services/*/manifests\n"
        "name: infra\n"
        "services:\n"
        f"{body}\n"
    )


def write_compose() -> Path:
    content = render_compose()
    COMPOSE_OUTPUT_PATH.write_text(content, encoding="utf-8")
    return COMPOSE_OUTPUT_PATH


def check_compose() -> bool:
    current = COMPOSE_OUTPUT_PATH.read_text(encoding="utf-8") if COMPOSE_OUTPUT_PATH.exists() else ""
    return current == render_compose()


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate docker compose from manifests")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when deploy/compose/docker-compose.yml is out of sync",
    )
    args = parser.parse_args()

    if args.check:
        if check_compose():
            print("compose is in sync")
            return
        raise SystemExit("generated compose is out of sync: run `python3 scripts/generate_compose.py`")

    path = write_compose()
    print(path)


if __name__ == "__main__":
    main()
