import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from shared.platform_service_catalog import list_platform_service_definitions
from shared.service_catalog import list_service_definitions

COMPOSE_OUTPUT_PATH = PROJECT_ROOT / "infra" / "docker-compose.yml"


def _indent(text: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" if line else line for line in text.splitlines())


def _render_platform_service(definition) -> str:
    lines = [f"{definition.service_name}:"]
    if definition.image is not None:
        lines.append(f"  image: {definition.image}")
        if definition.service_name == "redis":
            lines.append('  command: ["redis-server", "/usr/local/etc/redis/redis.conf"]')
    if definition.dockerfile is not None:
        lines.extend(
            [
                "  build:",
                f"    context: {definition.build_context}",
                f"    dockerfile: {definition.dockerfile}",
            ]
        )
    if definition.user is not None:
        lines.append(f'  user: "{definition.user}"')
    if definition.restart is not None:
        lines.append(f"  restart: {definition.restart}")
    if definition.env_files:
        lines.append("  env_file:")
        lines.extend(f"    - {_to_compose_env_file_path(path)}" for path in definition.env_files)
    if definition.ports:
        lines.append("  ports:")
        lines.extend(f'    - "{port}"' for port in definition.ports)
    if definition.volumes:
        lines.append("  volumes:")
        lines.extend(f"    - {volume}" for volume in definition.volumes)
    if definition.depends_on_service_healthy:
        lines.append("  depends_on:")
        for service_name in definition.depends_on_service_healthy:
            lines.extend(
                [
                    f"    {service_name}:",
                    "      condition: service_healthy",
                ]
            )
    if definition.healthcheck is not None:
        lines.extend(
            [
                "  healthcheck:",
                f"    test: [{', '.join(_quote_healthcheck_item(item) for item in definition.healthcheck.test)}]",
                f"    interval: {definition.healthcheck.interval}",
                f"    timeout: {definition.healthcheck.timeout}",
                f"    retries: {definition.healthcheck.retries}",
            ]
        )
    return "\n".join(lines)


def _render_worker_service(definition) -> str:
    env_files = "\n".join(f"    - {_to_compose_env_file_path(path)}" for path in definition.env_files)
    return f"""{definition.service_name}:
  build:
    context: ..
    dockerfile: {definition.dockerfile}
  user: "${{HOST_UID:-1000}}:${{HOST_GID:-1000}}"
  restart: unless-stopped
  env_file:
{env_files}
  volumes:
    - ../logs:/app/logs
  depends_on:
    redis:
      condition: service_healthy
  deploy:
    replicas: {definition.replicas}"""


def _to_compose_path(path: str) -> str:
    normalized = Path(path).as_posix()
    if normalized.startswith("infra/"):
        return normalized.removeprefix("infra/")
    return normalized


def _to_compose_env_file_path(path: str) -> str:
    normalized = Path(path).as_posix()
    if normalized.startswith("infra/"):
        return f"./{normalized.removeprefix('infra/')}"
    return f"../{normalized}"


def _quote_healthcheck_item(value: str) -> str:
    return f'"{value}"'


def render_compose() -> str:
    service_blocks = [_render_platform_service(definition) for definition in list_platform_service_definitions()]
    for definition in list_service_definitions():
        service_blocks.append(_render_worker_service(definition))

    body = "\n\n".join(_indent(block, 2) for block in service_blocks)
    return (
        "# Generated by scripts/generate_compose.py\n"
        "# Source of truth: infra/platform_services/*.json + domains/*/manifests/*.json\n"
        "services:\n"
        f"{body}\n"
    )


def write_compose() -> Path:
    content = render_compose()
    COMPOSE_OUTPUT_PATH.write_text(content, encoding="utf-8")
    return COMPOSE_OUTPUT_PATH


def main() -> None:
    path = write_compose()
    print(path)


if __name__ == "__main__":
    main()
