location = /context-platform-api {
    return 302 /context-platform-api/;
}

location /context-platform-api/ {
    set $context_platform_api_upstream http://context-platform-api:8000;
    rewrite ^/context\-platform\-api/(.*)$ /$1 break;
    proxy_pass $context_platform_api_upstream;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
}
