location = /context-platform {
    set $context_platform_dashboard_upstream http://context-platform-dashboard:3000;
    proxy_pass $context_platform_dashboard_upstream;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
}

location /context-platform/ {
    set $context_platform_dashboard_upstream http://context-platform-dashboard:3000;
    proxy_pass $context_platform_dashboard_upstream;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
}
